using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Threading;
using System.ComponentModel;
using System.IO;
using System.Data;

using ICSharpCode.AvalonEdit.Document;
using ICSharpCode.AvalonEdit;

using MipSim.Core;



namespace MipSim.IDE
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class SimulationWindow
    {
        List<Instruction> _instructions;
        List<Register> _registers;
        List<Memory> _memoryAddresses;
        List<ClockCycle> _clockcycles;
        DataTable _pipelinemap;
        CPU cpu;
        int currentClockCycle = 0;

        public SimulationWindow(List<Instruction> instructions, List<Register> registers, List<Memory> memoryAddresses)
        {
            InitializeComponent();
            _instructions = instructions;
            _registers = registers;
            _memoryAddresses = memoryAddresses;
            _clockcycles = new List<ClockCycle>();
            cpu = new CPU(instructions, registers, memoryAddresses);
            BindParameters();
        }

        private void BindParameters()
        {
            InstGrid.ItemsSource = _instructions;
            _registers.Where(x => x.Id == "R0").FirstOrDefault().HexValue = "0000000000000000";
            RegGrid.ItemsSource = _registers;
            MemGrid.ItemsSource = _memoryAddresses;
            ClockcycleGrid.ItemsSource = _clockcycles;
            InitializePipelineMap();
        }

        private void ExecuteClockCycle()
        {
            try
            {
                currentClockCycle++;
                var clockCycle = new ClockCycle(currentClockCycle);
                cpu.Execute();
                cpu.CopyInternalRegisters(clockCycle);
                _clockcycles.Add(clockCycle);
                ClockcycleGrid.Items.Refresh();
                RegGrid.Items.Refresh();
                RefreshPipelineMap(cpu.Pipeline, currentClockCycle);
            }
            catch(ExecutionEndException)
            {
                MessageBox.Show("End of Execution");
            }
        }

        private void InitializePipelineMap()
        {
            _pipelinemap = new DataTable();
            _pipelinemap.Columns.Add("Instruction");
            _pipelinemap.Columns.Add("Opcode");

            foreach (var inst in _instructions)
            {
                _pipelinemap.Rows.Add(inst.InstructionString, inst.OpcodeHex);
            }

            PipelineGrid.ItemsSource = _pipelinemap.DefaultView;
        }

        private void RefreshPipelineMap(Dictionary<String, String> pipeline, int clockcycle)
        {
            var clockcycleId = String.Format("CC {0}", clockcycle);
            _pipelinemap.Columns.Add(clockcycleId);

            for(int i = 0; i < _pipelinemap.Rows.Count; i++)
            {
                var key = _pipelinemap.Rows[i]["Opcode"].ToString();
                var item = pipeline.Where(p => p.Key == key).FirstOrDefault();
                if(!item.Equals(default(KeyValuePair<String,String>)))
                {
                    _pipelinemap.Rows[i][clockcycleId] = item.Value;
                }
            }
            PipelineGrid.ItemsSource = null;
            PipelineGrid.Items.Refresh();
            PipelineGrid.ItemsSource = _pipelinemap.DefaultView;
            PipelineGrid.Items.Refresh();
        }

        #region Event Handlers

        private void tbxGotoMem_TextChanged(object sender, TextChangedEventArgs e)
        {
            var currentText = tbxGotoMem.Text.ToUpper();
            var index = _memoryAddresses.FindIndex(m => m.Address.StartsWith(currentText));
            if (index != -1)
            {

                MemGrid.ScrollIntoView(MemGrid.Items[MemGrid.Items.Count - 1]);
                MemGrid.UpdateLayout();
                MemGrid.ScrollIntoView(MemGrid.Items[index]);
                MemGrid.SelectedItem = MemGrid.Items[index];
            }
        }

        private void menuStep_Click(object sender, RoutedEventArgs e)
        {
            ExecuteClockCycle();
        }

        private void PipelineGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var dataGridColumn in PipelineGrid.Columns)
            {
                if (dataGridColumn.DisplayIndex > 1)
                {
                    var textColumn = dataGridColumn as DataGridTextColumn;
                    if (textColumn == null) continue;

                    textColumn.ElementStyle = FindResource("ColumnStyle") as Style;
                }
            }
        }

        #endregion Event Handlers

      

       

        

    }
}
